### ISSUE TITLE
Error when clicking on `Manage` button in talawa-admin as Admin in `develop` branch

### ISSUE THREAD

**Issue by VanshikaSabharwal** [PalisadoesFoundation/talawa-admin#3598]
**Describe the bug**
1. An error `Error occured while loading data` is occuring when trying to click on `Manage` button in talawa-admin as a admin in `develop` branch
2. The login page briefly reappears, which may be the cause of the issue

**To Reproduce**

1. Login as admin in talawa-admin (`develop` branch)
2. Go to My Organizations
3. Click on `Manage` button

**Expected behavior**
- There must not be any error while trying to manage.

**Actual behavior**
- There is `Error occured while loading data` error occuring when trying to manage 

**Screenshots**
1. The user experience
    ![Image](https://github.com/user-attachments/assets/a8893e07-a807-4716-85c4-040625aaf5cf)
1. Developer tools
    ![Image](https://github.com/user-attachments/assets/7166523b-1c0d-4a31-b1df-b73103f470e9)

Video

https://github.com/user-attachments/assets/9622a4c8-76d7-4625-95f6-faf9bc18c357

**Additional details**
No

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by PurnenduMIshra129th** [comment]
@varshith257 please assign  .  @VanshikaSabharwal are you working on this issue.

**Comment by dhanagopu** [comment]
@PurnenduMIshra129th  Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by PurnenduMIshra129th** [comment]
@dhanagopu I am in doubt after the pr related to the issue is being also merged untill and unless the issue is not closed up to that point if it is showing the name also considered as assigned to that user ?If it is true then i will un assign my self from one issue.Because the later part which is now solved on the issue comment section is not related to that issue actually now they are handled by @VanshikaSabharwal

**Comment by Cioppolo14** [comment]
@PurnenduMIshra129th If you are no longer working on that issue/your part is complete, unassign yourself since it sounds like the issue must remain opened, and then you will get priority on this issue assignment.

**Comment by bandhan-majumder** [comment]
@palisadoes @Cioppolo14 can I work on this?

**Comment by prayanshchh** [comment]
this is the error

![Image](https://github.com/user-attachments/assets/87488305-8016-46b9-9a7c-88d881479b8a)

![Image](https://github.com/user-attachments/assets/44ec8e2e-3537-42aa-ac9b-e579aef80c41)

**Comment by prayanshchh** [comment]
I added the sample data, but the error is still there 

this might be the reason
![Image](https://github.com/user-attachments/assets/423d6d87-f7aa-4ced-82cd-45ae144fa1b8)

**Comment by prayanshchh** [comment]
this can also be the reason


logs in talawa-api container
`
talawa-api-dev        | [0] error 2025-02-15 13:19:53 gpq6enr4bn Transaction already in progress {"locations":[{"line":2,"column":3}],"path":["eventsByOrganizationConnection"],"extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["MongoTransactionError: Transaction already in progress","    at ClientSession.startTransaction (/usr/src/app/node_modules/mongoose/node_modules/mongodb/src/sessions.ts:374:13)","    at <anonymous> (/usr/src/app/src/helpers/event/createEventHelpers/createRecurringEventInstancesDuringQuery.ts:105:17)","    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","    at async Promise.all (index 2)","    at async createRecurringEventInstancesDuringQuery (/usr/src/app/src/helpers/event/createEventHelpers/createRecurringEventInstancesDuringQuery.ts:52:3)","    at async Object.eventsByOrganizationConnection (/usr/src/app/src/resolvers/Query/eventsByOrganizationConnection.ts:25:5)"]}} 
`

**Comment by prayanshchh** [comment]
I think this is a transaction error, I have introduced a check in the code that checks whether there is a existing transaction, if there is no existing transaction then only a new one is created.

@palisadoes I wanted to discuss the approach that might be causing the problem

1. Transactions are being reused across multiple recurrence rules.
2. The session is shared, causing multiple transactions to interfere.

this is happening as we have one shared session for all the recurrence rules, hence sometimes transactions are interfering.

**Comment by palisadoes** [comment]
This was working before. 

1. Why are recurring events being involved when selecting an organization?
1. Why does the login page briefly appear before the error message?

**Comment by palisadoes** [comment]
This may be the cause of the issue. The login page briefly reappears giving a 404 error.

![Image](https://github.com/user-attachments/assets/2b01eebe-1806-41e5-a278-12e6d249a643)

**Comment by prayanshchh** [comment]
![Image](https://github.com/user-attachments/assets/07bf35ff-901f-44a0-bf8e-dff42604ec40)

this is causing a CSRF error

![Image](https://github.com/user-attachments/assets/3ed7aaa6-a1b0-4cc9-aac0-05f1f7f433e9)


am trying to fix this, can u assign me this?

**Comment by prayanshchh** [comment]
the original issue is not arising from login page, however I did look into that, the problem is /graphql is giving CSRF error on GET requests.

Results in terminal
![Image](https://github.com/user-attachments/assets/f86dc974-a75a-467f-b473-7e57a1567a2f)

so I changed the code in login.tsx

![Image](https://github.com/user-attachments/assets/7cc38f54-1d2b-4b00-bd22-1133c2cbf20f)

and this is the results

![Image](https://github.com/user-attachments/assets/a81b95b9-56c2-408f-9927-c405d6acf3a2)

![Image](https://github.com/user-attachments/assets/1711e077-829f-4f05-a3b5-033ae700979d)


however I still get the orignal error, and there are multiple failed queries which might be the reason for this, 

query 1

![Image](https://github.com/user-attachments/assets/f883f434-5679-408e-9208-ffe103a4eb8b)

query 2

![Image](https://github.com/user-attachments/assets/befa185a-775a-46f2-86f7-22828d561fb1)

query 3

![Image](https://github.com/user-attachments/assets/e0dc88e8-0f31-4217-af59-90b1a9910262)

the response of all above mentioned queries is this

![Image](https://github.com/user-attachments/assets/bfda4a70-18d6-43d6-b476-42939f366433)


I will dive deeper into this now

**Comment by palisadoes** [comment]
1. Don't hard code `localhost` and port 4000 in the final PR. These values must come from the `.env` file.
2. In `develop` the endpoint is `/graphql/` in `develop-postgres` the endpoint is `/graphql`

**Comment by prayanshchh** [comment]
Got it, this was just for debugging

**Comment by VanshikaSabharwal** [comment]
> this is the error community is null ![Image](https://github.com/user-attachments/assets/87488305-8016-46b9-9a7c-88d881479b8a)
> 
> ![Image](https://github.com/user-attachments/assets/44ec8e2e-3537-42aa-ac9b-e579aef80c41)
> 
> ![Image](https://github.com/user-attachments/assets/6fbb272f-1875-41a0-9c88-5f3abd302cdc)
> 
> we don't have any sample data for community, this is not a importation error, we have not configured sample data for community in loadSampledata.ts

@palisadoes 

I have told you before as well @prayanshchh that the data in not in `talawa-dev` it is in `talawa-api` . You are using `talawa-dev` so how will you see the data.

**Comment by prayanshchh** [comment]
> > this is the error community is null ![Image](https://github.com/user-attachments/assets/87488305-8016-46b9-9a7c-88d881479b8a)
> > ![Image](https://github.com/user-attachments/assets/44ec8e2e-3537-42aa-ac9b-e579aef80c41)
> > ![Image](https://github.com/user-attachments/assets/6fbb272f-1875-41a0-9c88-5f3abd302cdc)
> > we don't have any sample data for community, this is not a importation error, we have not configured sample data for community in loadSampledata.ts
> 
> [@palisadoes](https://github.com/palisadoes)
> 
> I have told you before as well [@prayanshchh](https://github.com/prayanshchh) that the data in not in `talawa-dev` it is in `talawa-api` . You are using `talawa-dev` so how will you see the data.

1. data is in talawa-dev

![Image](https://github.com/user-attachments/assets/52024f0f-c3c5-4122-871a-2b7ddb00f96d)

2. this is not about community data, I think this is about failing graphql queries

**Comment by prayanshchh** [comment]
```
  query GetVolunteerRanks($orgId: ID!, $where: VolunteerRankWhereInput!) {
    getVolunteerRanks(orgId: $orgId, where: $where) {
      rank
      hoursVolunteered
      user {
        _id
        lastName
        firstName
        image
        email
      }
    }
  }
```

this query might be the reason for this error, I removed this query and is references from OrganizationDashboard page and the dashboard was loading successfully, as far as I remember the test for getVolunteerRanks was also failing a lot, @varshith257 was pushing to fix the implementation rather than the test. In the backend the rankedVolunteers is always an empty array.

![Image](https://github.com/user-attachments/assets/0dbe29d2-7621-49cc-8e10-49c7de2c9bd1)

Is there an ongoing issue for this? , I will spend my time fixing this and see whether it fixes our problem

**Comment by palisadoes** [comment]
Why does the login screen briefly flash? Is it because of the error?

**Comment by prayanshchh** [comment]
> This was working before.
> 
> 1. Why are recurring events being involved when selecting an organization?
> 2. Why does the login page briefly appear before the error message?

I forgot to answer this, this is why

![Image](https://github.com/user-attachments/assets/4b871c15-16a7-4666-ab00-11008c16ccac)

**Comment by prayanshchh** [comment]
I went on with the approach to use new session for every transaction, with this approach I was facing a write error, as diffrenct sessions in each transaction were trying to update same document, this was hapenning as creatorID for a lot of events was same hence when we were update user with ID creatorID, it was creating a write error.

![Image](https://github.com/user-attachments/assets/ae18c4a1-2a0d-4e3a-9ea9-681d7a4086f6)

file: `generateRecurringEventInstances.ts`
this file is refrenced in `createRecurrenceRule.ts` as after updating recurrence rules we generate the recurring events, this happens in a mongodb transaction.

these three were wrapped in a promise before, I removed this and I don't get the write error and I get directed to dashboard without any redirections.

@palisadoes

**Comment by palisadoes** [comment]
1. This used to work.
2. I think the best approach would be to identify the file(s) you think are causing the problem and take a look at their GitHub history for clues

**Comment by prayanshchh** [comment]
1. I ran the app locally instead of locally I still get the error
2. I will try this

**Comment by prayanshchh** [comment]
1. I checked the history of the file causing the error, I did not see any significant change that could be causing the transaction error, from the start the file is running transactions in parrallel using promise.all in a single session, which is not allowed according to mongodb documentation.

2. the only significant changes in the file were type fixes and documentation, but no changes in underlying logic of transactions.

**Comment by bandhan-majumder** [comment]
@prayanshchh looking into it. I have read the above discussion. Setting up and branch to reproduce the error. Will update the status.

**Comment by prayanshchh** [comment]
1. Not relates to this issue

2.when I was seeing docker logs, I saw logs for mongodb replset failing to intialize from out init-mongo.sh script, however replset was successfully initialized, the problem was that the mongo script was starting replset when replset was already initialised.
 
3. I fixed this just to confirm whether that was causing the issue. it was not.

4. If you want this change merged I can open a PR @palisadoes

**Comment by bandhan-majumder** [comment]
@prayanshchh @VanshikaSabharwal @palisadoes Everything is working fine. I have done the below;
1. using `develop` branch for api and admin
2. pulled the recent changes for both
3. logged in as admin.
4. clicked on manage
5. everything is working fine.

Proof: https://www.loom.com/share/c1570905d9e54f68824ea1d5143d74ed

I have waited til the completion of loading of event. Am I missing something?

**Comment by VanshikaSabharwal** [comment]
Amazing @bandhan-majumder  if everything is working fine.

**Comment by VanshikaSabharwal** [comment]
Are you using docker or local setup for this??

**Comment by bandhan-majumder** [comment]
@VanshikaSabharwal local as nowhere in the description/steps `docker` was mentioned. If it needs to be tested in docker, let me know.

**Comment by prayanshchh** [comment]
> [@VanshikaSabharwal](https://github.com/VanshikaSabharwal) local as nowhere in the description/steps `docker` was mentioned. If it needs to be tested in docker, let me know.

yes it needs to be tested in docker, but I got the same error when I did local setup.

**Comment by palisadoes** [comment]
> 1. Not related to this issue
> 
> 2. when I was seeing docker logs, I saw logs for mongodb replset failing to intialize from our init-mongo.sh script, however replset was successfully initialized, the problem was that the mongo script was starting replset when replset was already initialised.
>  
> 3. I fixed this just to confirm whether that was causing the issue. it was not.
> 
> 4. If you want this change merged I can open a PR @palisadoes 

OK

**Comment by palisadoes** [comment]
> @VanshikaSabharwal local as nowhere in the description/steps `docker` was mentioned. If it needs to be tested in docker, let me know. 

It falls when Docker is used for both Admin and API

**Comment by palisadoes** [comment]
Where are the application logs visible in the docker containers? I've set logging to YES in the Admin .env file and can't find them

**Comment by prayanshchh** [comment]
> Where are the application logs visible in the docker containers? I've set logging to YES in the Admin .env file and can't find them

yes I also don't see them, my branch must be behind upstream.

**Comment by prayanshchh** [comment]
you can reproduce this by logging in  [Talawa demo site](https://demo.talawa.io/) as a admin, and click on manage button.
however the issue can be reproduced both using docker or without it, can you confirm this @VanshikaSabharwal

**Comment by VanshikaSabharwal** [comment]
I have figured out that the issue is not docker specific. It occurs when the setup is local as well. I also saw that the problem is in the code maybe the `src/screens/OrganizationDashboard.tsx`. I wonder there is some case which is trigerring the situation where the page becomes unaccessible.

**Comment by VanshikaSabharwal** [comment]
Because other pages are working fine. and we have issue with `/orgevents` and `/orgdash` only and other pages are accessible.

**Comment by bandhan-majumder** [comment]
But why am I not able to reproduce the error in local setup then. Can we ask someone else to confirm it although you both are having @prayanshchh @VanshikaSabharwal

**Comment by prayanshchh** [comment]
> Because other pages are working fine. and we have issue with `/orgevents` and `/orgdash` only and other pages are accessible.

check the above comments in this issue, it tells why this issue occurs, I can't find a solution to the problem

**Comment by prayanshchh** [comment]
> But why am I not able to reproduce the error in local setup then. Can we ask someone else to confirm it although you both are having [@prayanshchh](https://github.com/prayanshchh) [@VanshikaSabharwal](https://github.com/VanshikaSabharwal)

the same issue occurs on the demo site, but sure go ahead

**Comment by prayanshchh** [comment]
new error in demo instance for super admin

https://github.com/user-attachments/assets/d1f3d43e-a5a9-42c6-b8b8-73225575d6a0

**Comment by VanshikaSabharwal** [comment]
@prayanshchh I have seen the comments but i am not sure abt the given reason. Still if you want to follow that approach and feel like you can solve this issue then go ahead.

**Comment by prayanshchh** [comment]
then can you give your reasoning as to why this is happening

**Comment by VanshikaSabharwal** [comment]
The more you change docker code unnecessarily, the more errors and issues will occur. This repl set issue is also a result of this. We solved this issue before and now it is again coming.

**Comment by VanshikaSabharwal** [comment]
Leave the docker as is and focus on edge cases covered in these files. 

> Because other pages are working fine. and we have issue with `/orgevents` and `/orgdash` only and other pages are accessible.

**Comment by prayanshchh** [comment]
> The more you change docker code unnecessarily, the more errors and issues will occur. This repl set issue is also a result of this. We solved this issue before and now it is again coming.

but this is not a docker-specific issue as you mentioned and repl set is not a issue the script was trying to start replset when replset was already initialized, this didn't affect the functioning of the app, however I still undo-ed it

**Comment by palisadoes** [comment]
1. I fixed the demo site yesterday. It must be a recently merged PR. 
2. Can someone check?

**Comment by VanshikaSabharwal** [comment]
> 1. I fixed the demo site yesterday. It must be a recently merged PR.
> 2. Can someone check?

Yes @palisadoes . 
@bandhan-majumder i think as peter solved this issue. This is why you were able to see the functionality of manage button

**Comment by prayanshchh** [comment]
> 1. I fixed the demo site yesterday. It must be a recently merged PR.
> 2. Can someone check?

were you talking about the page not found error in orglist, i think it is happening, as we are using `mongodb://localhost:27017/talawa-api` in the env, we should change it to dev, for me this worked

**Comment by palisadoes** [comment]
@prayanshchh 

Are you saying we should use this in the API `.env` file?
```
MONGO_DB_URL=mongodb://localhost:27017/talawa-dev
```

**Comment by prayanshchh** [comment]
> [@prayanshchh](https://github.com/prayanshchh)
> 
> Are you saying we should use this in the API `.env` file?
> 
> ```
> MONGO_DB_URL=mongodb://localhost:27017/talawa-dev
> ```

yes sir, we also changed it to dev in sample data file, it only makes sense that we connect to the db that has the right data.

**Comment by palisadoes** [comment]
1. When I run these commands with that setting:
    ```
    cd /home/talawa-api/talawa-api && docker compose -f docker-compose.dev.yaml down --rmi all --volumes && git checkout --force develop && git fetch upstream && git reset upstream/develop --hard && npm install && docker compose -f docker-compose.dev.yaml up --build -d --remove-orphans && docker exec talawa-api-dev /bin/bash -c "npm install -g pnpm && pnpm run import:sample-data && exit"
    ```
1. I get this error:
    ![Image](https://github.com/user-attachments/assets/3decae63-a352-4927-805b-addc28f1f781)

Should the DB be dropped first as part of the loading script?

**Comment by palisadoes** [comment]
@prayanshchh I tried replacing the contents of `events.json` with just `[]`. The DB load works, however the manage error persists.

@bandhan-majumder Have you had any success?

**Comment by prayanshchh** [comment]
I have tried debugging this,

> 1. When I run these commands with that setting:
>    ```
>    cd /home/talawa-api/talawa-api && docker compose -f docker-compose.dev.yaml down --rmi all --volumes && git checkout --force develop && git fetch upstream && git reset upstream/develop --hard && npm install && docker compose -f docker-compose.dev.yaml up --build -d --remove-orphans && docker exec talawa-api-dev /bin/bash -c "npm install -g pnpm && pnpm run import:sample-data && exit"
>    ```
> 2. I get this error:
>    ![Image](https://github.com/user-attachments/assets/3decae63-a352-4927-805b-addc28f1f781)
> 
> Should the DB be dropped first as part of the loading script?

I don't think the db should be dropped, we have made sure that db is reset after every import.

here's what I think is happening

1. we have a script that imports data automatically the moment api and db is up
2. when we specifically exec in api and import the data, this might be clashing with our automatic importation
3. either we can remove the script, or we can run the import command

**Comment by bandhan-majumder** [comment]
@palisadoes 

Updates:
1. able to fix the issue and it's working fine
preview: https://www.loom.com/share/02f02dc2ba6e401099d8096aaa4e9bbb
2. (low priority) getting a `MongoExpiredSessionError`. Will fix it so that no error occurs. But it's not hampering any request/response.

**Comment by prayanshchh** [comment]
What changes did u make?

**Comment by bandhan-majumder** [comment]
@palisadoes the changes are in api. Should I create a pr there and mention this issue?

**Comment by bandhan-majumder** [comment]
@prayanshchh the issue was how transactions were handled. We had to wait till one transaction is completed. Will open a pr so that the changes can be evaluated easily.

**Comment by prayanshchh** [comment]
> [@prayanshchh](https://github.com/prayanshchh) the issue was how transactions were handled. We had to wait till one transaction is completed. Will open a pr so that the changes can be evaluated easily.

if u used a for loop instead of promise approach it will fix the bug, but it blocks the whole site, the events will work but if you try to sign out and sign in again it won't work this will happen as node js process is out of memory, that's why I asked to explain your changes

**Comment by bandhan-majumder** [comment]
@prayanshchh you are right. But I am sure there is a fix too.

**Comment by prayanshchh** [comment]
1. @palisadoes mentioned it used to work before, `createRecurringEventInstancesDuringQuery` might not be the problem
2. I checked the file history, no change in underlying logic of transactions, so if this code used to work before, it should work now

**Comment by bandhan-majumder** [comment]
Looking into it. There are some solutions that stack overflow suggests. Will try them today.

**Comment by bandhan-majumder** [comment]
@palisadoes what are the specifications of the instance where demo website is running on?

**Comment by palisadoes** [comment]
In what sense?

**Comment by bandhan-majumder** [comment]
@palisadoes RAM. I am thinking of increasing the size limit of docker. I have gone through the solutions and most of them are saying the same.
for ref: https://stackoverflow.com/questions/67903114/javascript-heap-out-of-memory-in-docker-image-run

**Comment by palisadoes** [comment]
![Image](https://github.com/user-attachments/assets/87f3f088-77b3-44fc-aa43-d3966d5d0edb)

**Comment by prayanshchh** [comment]
increasing space won't help @bandhan-majumder, as rrules increase more space will be required, this is not optimal, the test `eventsByOrganizationConnection.spec.ts` is passing, although we have only one rrules for testorganization._id this doesn't matter cuz it's working with 2 rrules as well, this points me to a issue in frontend.

**Comment by prayanshchh** [comment]
also I don't think sample data is the issue, if it worked before then it should work now as sample data also hasn't changed for a long time

**Comment by prayanshchh** [comment]
unassigning as no progress

**Comment by prayanshchh** [comment]
please unassign, as no progress

**Comment by palisadoes** [comment]
This is the latest variant of the error on the latest `develop` code.

https://github.com/user-attachments/assets/7c52474a-5168-4da6-893a-6941f5666b86
